# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Bridge at Waterloo
email: thebridgeatwaterloo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A bridge to a better future, improving young people’s chances of finding employment or creating their own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bridgeatwaterloo.org" # the base hostname & protocol for your site
twitter_username: TBAWaterloo
github_username:  bridgeatwaterloo

# Build settings
markdown: kramdown
